### ISSUE TITLE
Crystal 0.36.0 breaks this library

### ISSUE THREAD

**Issue by munjalpatel** [kaukas/crystal-cassandra#3]
Hello,

Just upgraded to Crystal 0.36.0 and seeing the following error when trying to compile the project:

```
In lib/cassandra/src/cassandra/dbapi/session.cr:9:5

 9 | class Session < DB::Connection
     ^
Error: abstract `def DB::Connection#build_prepared_statement(query)` must be implemented by Cassandra::DBApi::Session
```

**Comment by kaukas** [comment]
Thank you for reporting! Fixed by https://github.com/kaukas/crystal-cassandra/commit/7b31dbb2ff60760beea8d43c1c23f11b9570f1bc.
